name: semantic-photos
dependencies:
  - conda-forge::pillow
  - pip
  - python=3.12
  - requests
  - pip:
    - -r requirements-cuda.txt
    - chromadb
    - gradio
    - langchain
    - pillow-heif
    - sentence-transformers
    - transformers